### ISSUE TITLE
some problems about teraranger one

### ISSUE THREAD

**Issue by meshaohy** [Terabee/teraranger#12]
I have finished to build and run the package from source
$ cd ~/ros_ws/src
$ git clone https://github.com/Terabee/teraranger.git
$ cd ~/ros_ws
$ catkin_make
$ source devel/setup.bash
But when I ran the Teraranger one use the command $ rosrun teraranger one _portname:=/dev/ttyUSB0, 
I got the following error:
![teraranger one problem](https://user-images.githubusercontent.com/38443575/38838713-6c78aeaa-418c-11e8-88dd-ecc49459a7f3.png)

I have no idea where this error is coming from. What other steps can I take? Thank you!

**Comment by pl-kabaradjian** [comment]
Hello Meshaohy,

This is most likely a permission issue. Can you run the following command and post the output (make sure that the Teraranger One is connected and powered) : ls -lah /dev/tty*

Cheers,

**Comment by meshaohy** [comment]
Yes, the result is followed
![2](https://user-images.githubusercontent.com/38443575/38839178-458a8f6e-418e-11e8-8d61-256c8b512629.png)

**Comment by meshaohy** [comment]
![3](https://user-images.githubusercontent.com/38443575/38839261-ad4e83f8-418e-11e8-9758-23b3112fb165.png)
@pl-kabaradjian

**Comment by pl-kabaradjian** [comment]
As expected the sensor is detected as /dev/ttyUSB0 but the permission is not correct
You can temporarily fix it by allowing access to everyone : sudo chmod 666 /dev/ttyUSB0
If you want a permanent solution you need to add yourself to the 'dialout' group : sudo usermod -a -G dialout $USER

For the last one you need to logout and login in order effect.

Cheers,

**Comment by meshaohy** [comment]
But there still have some problems (:
![4](https://user-images.githubusercontent.com/38443575/38839544-009bd2c6-4190-11e8-9cff-48ae3da0c250.png)

**Comment by pl-kabaradjian** [comment]
This error can happen once when starting the driver. However, if this error line repeats several time there might be some connections issues.

Are you still having errors ?

**Comment by meshaohy** [comment]
@pl-kabaradjian Thanksyou. I'll try again tommorrow. I will promptly inform you of the results of the operation. Thanks again.

**Comment by meshaohy** [comment]
@pl-kabaradjian It still doesn't work, and the error is same to the above. But  I can get the data by the following command
$ screen /dev/ttyUSB0 115200
The software enviorment is Ubuntu16.04+kinetic.
Have you ever used Teraranger one? And do you have other suggestions? 
Thanks!

**Comment by pl-kabaradjian** [comment]
@meshaohy Just to clarify, how many times does this error line repeat after launching the driver? 
Did you check that you get Range messages in / teraranger_one?

**Comment by msadowski** [comment]
@meshaohy I just did a clean ROS install and the sensor is working for me as expected. 
I also see the line "Timeout or error while reading serial", however I get this error only once when I start the driver. When I leave this node running and in another terminal window execute "rostopic echo /teraranger_one" I can see the sensor readings appearing as expected.

**Comment by meshaohy** [comment]
@pl-kabaradjian @msadowski Thanks for replying! 
@msadowski Your method is worked! Thank you so much!
