### ISSUE TITLE
Terabee 64px Serial won't read

### ISSUE THREAD

**Issue by joshs333** [Terabee/teraranger#19]
Hello;

I was trying to use the Evo 64px with the python ros node.
https://github.com/Terabee/teraranger/blob/e17d8d795fe7f32c7acd28a2d5d272f8e447ba18/scripts/evo_64px.py#L271-L274

Initialization of the Evo_64px() object completes successfully, the run() gets called.
https://github.com/Terabee/teraranger/blob/e17d8d795fe7f32c7acd28a2d5d272f8e447ba18/scripts/evo_64px.py#L221-L223

port.flushInput() finishes successfully then start_sensor() gets called.
https://github.com/Terabee/teraranger/blob/e17d8d795fe7f32c7acd28a2d5d272f8e447ba18/scripts/evo_64px.py#L213-L215

send_command() gets called
https://github.com/Terabee/teraranger/blob/e17d8d795fe7f32c7acd28a2d5d272f8e447ba18/scripts/evo_64px.py#L189-L192

It calls port.write() then gets stuck on the port.read() and doesn't move past that line (192).

I'm not sure what's going on. The GUI on windows connects successfully and displays information. Any thoughts?

Thanks;
Josh

**Comment by pl-kabaradjian** [comment]
Hello @joshs333,

I am from Terabee, I invite you to contact support [here](https://www.terabee.com/about-us/contact/) (if not done already) so we can better assist you. Please also provide information about your setup such as : 
- ROS version
- platform and OS
- Are you using other sensors from us?

Best regards,

**Comment by joshs333** [comment]
Information provided/submitted. Will update this thread as issue progresses.

**Comment by pl-kabaradjian** [comment]
Hello @joshs333 if your issue is solved, please close it. I will leave it open for a few days so you can add comments if necessary.

Regards,

**Comment by joshs333** [comment]
The issue is not solved. I responded to the ticket online.

Thanks.
