### ISSUE TITLE
Teraranger DUO warning and no ultrasound on rostopic

### ISSUE THREAD

**Issue by Yuuded** [Terabee/teraranger#20]
When i'm starting the node for Teraranger DUO i get a warning message saying  **expected TerarangerDuo but TerarangerOne is detected**:
![screenshot from 2018-11-20 22-24-59](https://user-images.githubusercontent.com/19821829/48807176-a2b99400-ed14-11e8-8e09-6098b24ec686.png)
Is this of concern ? or Could it bad installation ?
Also when i use **rostopic echo /teraranger_duo/ultrasound** i get no output:
![screenshot from 2018-11-20 22-44-45](https://user-images.githubusercontent.com/19821829/48807606-ed87db80-ed15-11e8-87b6-f6fde469a7e5.png)

I'm using the usb-adapter supplied by terabee, Teraranger DUO, OS: Ubuntu 16.04.05 LTS. ROS:Kinetic.

**Comment by pl-kabaradjian** [comment]
Hello @Yuuded,

There might indeed be an issue with the sensor. In any case, I invite you to contact support [here](https://www.terabee.com/about-us/contact/) (if not done already) so we can better assist you. Please include your screenshots as well it is always helpful.

Best regards,
Pierre-Louis
