### ISSUE TITLE
64px fails if not in mode "distance + ambient" when starting

### ISSUE THREAD

**Issue by mortenfyhn** [Terabee/teraranger#22]
The 64px can be configured to either produce only distance output (64 values), or distance and "ambient" output (2 * 64 values). The driver appears to require the sensor to be configured for distance and ambient before it starts. Otherwise the ros node fails to read frames:

![invalidframelength](https://user-images.githubusercontent.com/6639836/53955085-5124f180-40d8-11e9-8596-4a24e684eb3c.png)

Probably the sensor interface should explicitly set the desired mode at startup, instead of assuming that the sensor already is in the correct mode.

By the way, do you have documentation for what the "ambient values" are? I'm not sure how to interpret them.

**Comment by pl-kabaradjian** [comment]
Hi @mortenfyhn,

Thanks a lot for the feedback. Concerning the ambient, it's an arbitrary value given by the sensor which represents the intensity of light in the wavelength of the sensor. We didn't make it available (in ROS) as it has more a debug and information purpose (detect other infra-red sources for instance). You can find more info in our user manual [here](https://www.terabee.com/wp-content/uploads/2018/10/TeraRanger-Evo-64px-user-manual.pdf).

On the driver side, you are right the driver should not assume one of the two modes. To fix that, there are several ways:

- Allow 141 and 256 bytes long frames -> ok as distance is always before ambient but a bit dirty
- Force ambient + distance at start -> but overrides sensor/user settings
- Change dynamically when ambient topic is subscribed, this would imply to rework the driver parse the ambient and publish it

We are quite busy on other products right now, so it will be hard to squeeze big changes in our schedule (I'll add it to the backlog though). I'll try to release the first fix in the next weeks to prevent the driver from hanging.

As usual, feel free to submit a pull-request if you want, we will be more than happy to review it.

Cheers,
Pierre-Louis

**Comment by mortenfyhn** [comment]
Thanks for the reply. I think option 2 is fine, so I'll try to submit a PR for it soon.
