### ISSUE TITLE
Timeout or error while reading serial

### ISSUE THREAD

**Issue by SunLengyi** [Terabee/teraranger#28]
When I run teraranger_one in the terminal，the instruction is  rosrun teraranger_array teraranger_one _portname:=/dev/ttyUSB0,I have an error about  
[ INFO] [1557042013.918755836]: node namespace: []
[ INFO] [1557042013.919873552]: [/teraranger_hub_one] is up and running with the following parameters:
[ INFO] [1557042013.919901913]: [/teraranger_hub_one] portname: /dev/ttyUSB0
[ERROR] [1557042014.935275372]: Timeout or error while reading serial
My software environment is Ubuntu16.04+kinetic
How can I solve it?Thanks!

**Comment by pl-kabaradjian** [comment]
Hello @SunLengyi ,
Can you tell us what product are you using?
Also, this is the "teraranger" repository which is about single sensors only. If your issue concerns arrays products such as Tower, Hub or Multiflex, then I invite you to raise an issue in the "teraranger_array" repository.
Cheers

**Comment by SunLengyi** [comment]
I use teraranger_one
Your suggestion is very good, thank you

**Comment by pl-kabaradjian** [comment]
Hey @SunLengyi ,
Is your issue solved? If yes, please feel free to close the issue and add details on how you solved it.
Cheers
