### ISSUE TITLE
Measured range is INVALID_MEASURE.

### ISSUE THREAD

**Issue by misoragod** [Terabee/teraranger#30]
Hi ALL,
I am using teraranger_evo on my rover in oder to detect objects. 
But the range which is measured by teraranger_evo is INVALID_MEASURE. 
This phenomenon sometimes happens. 
I want to know the reason for this phenomenon.

**Comment by pl-kabaradjian** [comment]
Hello @misoragod ,

To put it shortly this is the error code when the sensor is unable to measure and this can happen for various reasons.
As this question goes beyond the scope of this repository, I invite you to contact our support team [here](https://www.terabee.com/contact/) explaining your issue for further information or troubleshooting if necessary.

Have a nice day,

**Comment by pl-kabaradjian** [comment]
[()](url)

**Comment by misoragod** [comment]
Hello @pl-kabaradjian 

Thank you for your quick reply.
I got it.
