### ISSUE TITLE
[EVO_THERMAL.PY][ROS MELODIC]

### ISSUE THREAD

**Issue by Tahsinmullick** [Terabee/teraranger#34]
evo_thermal.py won't work on ros melodic.
Installed teraranger through clone and catkin_make, when run evo_thermal.py, the following error displayed.

sgt_pepper@lhcb:~$ rosrun teraranger evo_thermal.py 
[INFO] [1578339294.561081]: Starting sensor output...
[INFO] [1578339294.568021]: Sensor output started successfully
Traceback (most recent call last):
  File "/home/sgt_pepper/catkin_ws/src/teraranger-master/scripts/evo_thermal.py", line 340, in <module>
    evo_thermal.run()
  File "/home/sgt_pepper/catkin_ws/src/teraranger-master/scripts/evo_thermal.py", line 328, in run
    thermal_image = self.auto_scaling(temp_array)
  File "/home/sgt_pepper/catkin_ws/src/teraranger-master/scripts/evo_thermal.py", line 178, in auto_scaling
    frame = cv2.applyColorMap(frame, self.selected_cmap)
TypeError: only size-1 arrays can be converted to Python scalars

any thoughts?

**Comment by pl-kabaradjian** [comment]
Hello @Tahsinmullick ,

I am from Terabee, my initial guess would be that melodic uses a different version of OpenCV and loading a custom colormap is not working as expected. 

Can you please provide your OpenCV version (in a terminal where your ROS workspace is sourced)?

You can do that by opening a python shell and type the following:
>import cv2
>cv2.\_\_version\_\_

I personally have '3.3.1-dev' on kinetic.

As a workaround, you could use built-in OpenCV colormap such as JET or HOT.

Best regards,

**Comment by Tahsinmullick** [comment]
Sure the opencv version I have is 3.2.0
How should i use the builtin maps like HOT? 
It will be really great if you could let me know what line should I add and where?

**Comment by Tahsinmullick** [comment]
-I got it working by manually typing in COLORMAP_JET.

Which colormap is good for the Thermal Cameras to specially isolate a hot object better from cooler objects?

**Comment by pl-kabaradjian** [comment]
Hello @Tahsinmullick ,

I am glad that you found a way to solve your issue. Concerning the colormaps, JET and HOT are both good options (other colormaps avaliable for 3.2 [here](https://docs.opencv.org/3.2.0/d3/d50/group__imgproc__colormap.html#ga9a805d8262bcbe273f16be9ea2055a65)).

Beyond colormaps, value scaling will also influence contrast between temperatures.
I invite you to play with the dynamic reconfigure (`rosrun rqt_reconfigure  rqt_reconfigure`) interface which allows you to tune min and max temperatures values used for scaling to 8bits (which is then colormapped to RGB).

Cheers,
