### ISSUE TITLE
Licensing terms

### ISSUE THREAD

**Issue by krisklau** [Terabee/teraranger#6]
Hi,

It would be very advantageous to supply and describe under which license the software is published under.

**Comment by msadowski** [comment]
Hi @krisklau,

You raised a very good point. Currently the license information is contained in package.xml file (GPLv3).

 I'll revisit the license with the team to make sure we use the best one we can that doesn't impose too many restrictions on users.

**Comment by pl-kabaradjian** [comment]
Hi @krisklau we updated our license term to MIT(see PR #10).
Closing the issue.
